-- Create hand history table
create table if not exists public.hand_history (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null unique,
    hands_json jsonb not null default '[]'::jsonb,
    updated_at timestamptz default now()
);

-- Enable RLS
alter table public.hand_history enable row level security;

-- Create policies
create policy "Users can view their own hand history"
    on public.hand_history for select
    using (auth.uid() = user_id);

create policy "Users can insert their own hand history"
    on public.hand_history for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own hand history"
    on public.hand_history for update
    using (auth.uid() = user_id);

-- user_id unique constraint already creates the index used by upsert(on conflict user_id)
