-- Create statistics table
create table if not exists public.statistics (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null unique,
    balance numeric default 1000,
    wins integer default 0,
    losses integer default 0,
    blackjacks integer default 0,
    total_winnings numeric default 0,
    updated_at timestamptz default now()
);

-- Enable RLS
alter table public.statistics enable row level security;

-- Create policies
create policy "Users can view their own statistics"
    on public.statistics for select
    using (auth.uid() = user_id);

create policy "Users can insert their own statistics"
    on public.statistics for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own statistics"
    on public.statistics for update
    using (auth.uid() = user_id);
